backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/uploads"
public_folder: "uploads"
site_url: https://jolly-ramanujan-fbfd07.netlify.com
logo_url: https://jolly-ramanujan-fbfd07.netlify.com/assets/static/logo.7b22250.3ea91e7.png


collections:
  - name: "settings" # Used in routes, e.g., /admin/collections/blog
    label: "Einstellungen" # Used in the UI
    delete: false
    files:
      - label: "Impressum"
        name: "impressum"
        file: "markdown/settings/impressum.yml"
        fields:
          - {label: "Inhaber", name: "owner", widget: "string", required: false}
          - {label: "E-Mail", name: "email", widget: "string", required: false}
          - label: "Geschäftsadresse"
            name: "address"
            widget: "object"
            fields: 
              - {label: "Firma", name: "company", widget: "string", required: false}
              - {label: "Strasse und Hausnummer", name: "street", widget: "string", required: false}
              - {label: "PLZ", name: "zip", widget: "string", required: false}
              - {label: "Stadt", name: "city", widget: "string", required: false}
              - {label: "Geschäftl. Telefonnummer", name: "phone", widget: "string", required: false}
          - label: "Handelsregister"
            name: "register"
            widget: "object"
            fields: 
              - {label: "Amtsgericht", name: "court", widget: "string", required: false}
              - {label: "Handelsregisternummer", name: "hra", widget: "string", required: false}
              - {label: "UstId-Nr", name: "ustidnr", widget: "string", required: false}
          - label: "Datenschutz"
            name: "dataProtection"
            widget: "object"
            fields: 
              - {label: "Datenschutz-Beauftragter", name: "officer", widget: "string", required: false}
              - {label: "Strasse und Hausnummer", name: "street", widget: "string", required: false}
              - {label: "PLZ", name: "zip", widget: "string", required: false}
              - {label: "Stadt", name: "city", widget: "string", required: false}
      - label: "Location"
        name: "location"
        file: "markdown/settings/location.yml"
        fields:
          - {label: "Firma", name: "company", widget: "string", required: false}
          - {label: "Slogan", name: "slogan", widget: "string", required: false}
          - {label: "Öffentliche Telefonnummer", name: "phone", widget: "string", required: false}
          - {label: "Kontakt E-Mail", name: "email", widget: "string", required: false}
          - label: "Adresse"
            name: "address"
            widget: "object"
            fields: 
              - {label: "Strasse und Hausnummer", name: "street", widget: "string", required: false}
              - {label: "PLZ", name: "zip", widget: "string", required: false}
              - {label: "Stadt", name: "city", widget: "string", required: false}
          - label: "Öffnungszeiten"
            name: "openingHours"
            widget: "object"
            fields: 
              - {label: "Vorübergehend geschlossen", name: "closed", widget: "boolean", default: false}
              - {label: "Montags von", name: "mondayFrom", widget: "string", required: false}
              - {label: "Montags bis", name: "mondayTo", widget: "string", required: false}
              - {label: "Dienstags von", name: "tuesdayFrom", widget: "string", required: false}
              - {label: "Dienstags bis", name: "tuesdayTo", widget: "string", required: false}
              - {label: "Mittwochs von", name: "wednesdayFrom", widget: "string", required: false}
              - {label: "Mittwochs bis", name: "wednesdayTo", widget: "string", required: false}
              - {label: "Donnerstags von", name: "thursdayFrom", widget: "string", required: false}
              - {label: "Donnerstags bis", name: "thursdayTo", widget: "string", required: false}
              - {label: "Freitags von", name: "fridayFrom", widget: "string", required: false}
              - {label: "Freitags bis", name: "fridayTo", widget: "string", required: false}
              - {label: "Samstags von", name: "saturdayFrom", widget: "string", required: false}
              - {label: "Samstags bis", name: "saturdayTo", widget: "string", required: false}
              - {label: "Sonntags von", name: "sundayFrom", widget: "string", required: false}
              - {label: "Sonntags bis", name: "sundayTo", widget: "string", required: false}
              - {label: "Feiertags von", name: "holidayFrom", widget: "string", required: false}
              - {label: "Feiertags bis", name: "holidayTo", widget: "string", required: false}
      - label: "Social Media"
        name: "socialMedia"
        file: "markdown/settings/social-media.yml"
        fields: 
          - {label: "Facebook", name: "facebook", widget: "string", required: false}
          - {label: "Instagram", name: "instagram", widget: "string", required: false}
          - {label: "Youtube", name: "youtube", widget: "string", required: false}
          - {label: "Twitter", name: "twitter", widget: "string", required: false}
  - name: "contentPage" # Used in routes, e.g., /admin/collections/blog
    label: "Seite" # Used in the UI
    folder: "markdown/contentPage" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Seitenbeschreibung", name: "meta", widget: "string", required: false}
      - label: "Menü"
        name: "menu"
        widget: "select"
        options:
          - { label: "Hauptmenü", value: "main" }
          - { label: "Minimenü", value: "top" }
          - { label: "Footermenü", value: "footer" }
      - {label: "Position", name: "position", widget: "number", valueType: "float"}
      - {label: "Hintergrundbild", name: "featuredImage", widget: "image", required: false}
      - label: "FAQ"
        name: "faq"
        widget: "list"
        fields:
          - label: "Frage"
            name: "question"
            widget: "object"
            fields: 
              - {label: "Frage", name: "question", widget: "string"}
              - {label: "Antwort", name: "answer", widget: "string"}
      - label: "Galerie"
        name: "gallery"
        widget: object
        fields:
          - label: "Bild"
            name: "image"
            widget: "list"
            fields: 
              - {label: "Bild", name: "galleryImage", widget: "image"}
              - {label: "Copyright", name: "copyright", widget: "string", required: false}
      - {label: "Content", name: "body", widget: "markdown", required: false}
  - name: "category" # Used in routes, e.g., /admin/collections/blog
    label: "Produkt | Kategorie" # Used in the UI
    folder: "markdown/category" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Kategoriebild", name: "featuredImage", widget: "image"}
      - {label: "Beschreibung der Kategorie", name: "description", widget: "string"}
      - label: "Übergeordnete Kategorie"
        name: "subcategory"
        widget: "relation"
        collection: "category"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
        required: false
  - name: "manufacturer" # Used in routes, e.g., /admin/collections/blog
    label: "Produkt | Hersteller" # Used in the UI
    folder: "markdown/manufacturer" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "Hersteller", name: "description", widget: "string"}
  - name: "product" # Used in routes, e.g., /admin/collections/blog
    label: "Produkt" # Used in the UI
    folder: "markdown/product" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Verfügbar", name: "available", widget: "boolean", default: true}
      - {label: "Name", name: "title", widget: "string"}
      - label: "Kategorie(n)"
        name: "category"
        widget: "relation"
        multiple: true
        collection: "category"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
        required: false
      - label: "Hersteller"
        name: "manufacturer"
        widget: "relation"
        collection: "manufacturer"
        searchFields: ["title"]
        valueField: "title"
        displayFields: ["title"]
        required: false
      - {label: "Preis", name: "price", widget: "number", valueType: "float"}
      - {label: "Video URL", name: "video", widget: "string"}
      - label: "Produktbild"
        name: "featuredImage"
        widget: "image"
      - {label: "Content", name: "body", widget: "markdown"}
      - label: "Rabatt"
        name: "discount"
        widget: "object"
        fields: 
          - {label: "Aktiv", name: "active", widget: "boolean", default: false}
          - {label: "Rabatt in Prozent", name: "percentage", widget: "number", valueType: "float", required: false}
          - {label: "Von", name: "dateFrom", widget: "date", dateFormat: true, required: false}
          - {label: "Bis", name: "dateTo", widget: "date", dateFormat: true, required: false}